kind: Service
apiVersion: v1
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${APP_NAME}
    tier: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
    tier: backend
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30012
      name: ${APP_NAME}