apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  ports:
    - nodePort: 30306
      port: 30306
      targetPort: 3306
      name: mariadb
  selector:
    app: mariadb

