kind: Service
apiVersion: v1
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${APP_NAME}
    tier: backend
  namespace: default
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
    tier: backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30014
      name: ${APP_NAME}