kind: Service
apiVersion: v1
metadata:
  name: msa-sample-sd-api
  labels:
    app: msa-sample-sd-api
    tier: backend
spec:
  type: NodePort
  selector:
    app: msa-sample-sd-api
    tier: backend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30014
      name: msa-sample-sd-api
